### ISSUE TITLE
Update for Elm 0.17

### ISSUE THREAD

**Issue by jasondew** [srid/heroku-buildpack-elm#16]
Just checking on the status of the upgrade. Thanks for making the buildpack!

**Comment by vorce** [comment]
Maybe the elm version could be an option in the app.json?

Edit: Oh, I can just add ELM_VERSION=0.17 to a file called .buildpack.env and it sets it correctly to 0.17. Cool! However the assets for that version doesn't exist yet.

**Comment by mordrax** [comment]
yep, getting the same thing, please update for 0.17

```
mordrax@mordrax-desktop:~/code/cotwelm$ git push heroku master
Counting objects: 58, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (49/49), done.
Writing objects: 100% (58/58), 889.13 KiB | 0 bytes/s, done.
Total 58 (delta 4), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching set buildpack https://github.com/srid/heroku-buildpack-elm.git... done
remote: -----> Elm app detected
remote: -----> Retrieving 0.17
remote: https://s3.amazonaws.com/heroku-buildpack-elm/assets/elm/0.17/elm:
remote: 2016-05-14 06:23:48 ERROR 403: Forbidden.
remote: 
remote:  !     Push rejected, failed to compile Elm app
remote: 
remote: Verifying deploy....
remote: 
remote: !   Push rejected to cotwelm.
remote: 
To https://git.heroku.com/cotwelm.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/cotwelm.git'
```

**Comment by mordrax** [comment]
Guys, this is a pretty awesome workaround if you just want to expose index.html for a poc.
http://stackoverflow.com/a/17531897/256272
if you follow the comments to that answer, it's even easier!

summary:
1. `elm-make <main_elm_file> --output index.html && mv index.html index.php`
2. `git commit -am '<blah blah blah>' && git push heroku master`

Heroku will treat your app as a php app (auto install heroku/php buildpack) and run index.php which just works!

You have to remove the elm buildpack.

You no longer need `app.json` or `.buildpack.env` since you're building the html locally.

**Comment by srid** [comment]
Apologies! Github notifications is pretty sucky; the notifications for my personal repos got buried among (the huge amount of) organization notifications, so I had failed to act on them promptly.

I'll update to 0.17 soon.

**Comment by jasondew** [comment]
Thanks @srid !

**Comment by vorce** [comment]
Yes thanks a lot @srid
